- name: 🔐 Config Dosyasını Kasadan Oluştur
      run: |
        cat << EOF > config.py
        BASE_URL = "https://admin.nnaconnected.com"
        VIN = "${{ secrets.VIN }}"
        AUTH_ENDPOINT = "/api/idm/api/client_token"
        API_KEY = "${{ secrets.API_KEY }}"
        APP_TYPE = "WEB_APP"
        CLIENT_ID = "${{ secrets.CLIENT_ID }}"
        CLIENT_SECRET = "${{ secrets.CLIENT_SECRET }}"
        OEM_ID = "${{ secrets.OEM_ID }}"
        ACCOUNT_ID = "${{ secrets.ACCOUNT_ID }}"
        REMOTE_DOOR_ENDPOINT = f"/api/telematics/oem/{OEM_ID}/accounts/{ACCOUNT_ID}/remote-door"
        REMOTE_ENGINE_ENDPOINT = f"/api/telematics/oem/{OEM_ID}/accounts/{ACCOUNT_ID}/remote-engine"
        LOCATION_POST_ENDPOINT = f"/api/telematics/oem/{OEM_ID}/accounts/{ACCOUNT_ID}/location"
        EOF
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        VIN: ${{ secrets.VIN }}
        OEM_ID: ${{ secrets.OEM_ID }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
